PIM/Controllers/ChamadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PIM.Models.Repository;
using PIM.Models.Objects;
using PIM.Controllers.Repository;
using System.Data;

namespace PIM.Controllers
{
    public class ChamadoController : BaseController
    {
        private IChamadoRepositorio _repositorio;

        public ChamadoController() :this(new ChamadoRepositorio())
        {
        }

        public ChamadoController(IChamadoRepositorio repositorio)
        {
            ViewBag.Title = "Chamados";
            _repositorio = repositorio;
        }

        public ActionResult Index()
        {
            var chamado = _repositorio.GetChamado();
            return View(chamado);
        }

        public ActionResult Details(int id)
        {
            Chamado model = _repositorio.GetChamado(id).First();
            return View(model);
        }

        public ActionResult Create()
        {
            List<SelectListItem> grauItems = new List<SelectListItem>();
            List<SelectListItem> departamentoItems = new List<SelectListItem>();
            List<SelectListItem> clienteItems = new List<SelectListItem>();
            List<SelectListItem> funcionarioItems = new List<SelectListItem>();
            List<SelectListItem> atribuicaoItems = new List<SelectListItem>();

            IGrauUrgenciaRepositorio _grauRepo = new GrauUrgenciaRepositorio();
            foreach (var GP in _grauRepo.GetGrauUrgencia())
            {
                grauItems.Add(new SelectListItem { Text = GP.Nome, Value = GP.id.ToString() });
            }

            IDepartamentoRepositorio _depRepo = new DepartamentoRepositorio();
            foreach (var DR in _depRepo.GetDepartamento())
            {
                departamentoItems.Add(new SelectListItem { Text = DR.Nome, Value = DR.id.ToString() });
            }

            IClienteRepositorio _clienteRepo = new ClienteRepositorio();
            foreach (var CR in _clienteRepo.GetCliente())
            {
                clienteItems.Add(new SelectListItem { Text = CR.Nome, Value = CR.id.ToString() });
            }

            IFuncionarioRepositorio _funcRepo = new FuncionarioRepositorio();
            foreach (var FR in _funcRepo.GetFuncionario())
            {
                funcionarioItems.Add(new SelectListItem { Text = FR.Nome, Value = FR.id.ToString() });
            }

            IAtribuicaoRepositorio _atribRepo = new AtribuicaoRepositorio();
            foreach (var AR in _atribRepo.GetAtribuicao())
            {
                atribuicaoItems.Add(new SelectListItem { Text = AR.Nome, Value = AR.id.ToString() });
            }

            ViewBag.GrauUrgenciaID = grauItems;
            ViewBag.DepartamentoID = departamentoItems;
            ViewBag.ClienteID = clienteItems;
            ViewBag.FuncionarioID = funcionarioItems;
            ViewBag.AtribuicaoID = atribuicaoItems;

            return View(new Chamado());
        }
        [HttpPost]
        public ActionResult Create(Chamado chamado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.InserirChamado(chamado);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(chamado);
        }

        public ActionResult Edit(int id)
        {
            //Chamado model = _repositorio.GetChamadoPorID(id);
            Chamado model = _repositorio.GetChamado(ID: id).First();

            /*List<SelectListItem> items = new List<SelectListItem>();

            ISetorRepositorio _setorRepo = new SetorRepositorio();
            foreach (var SR in _setorRepo.GetSetor())
            {
                items.Add(new SelectListItem { Text = SR.Nome, Value = SR.id.ToString(), Selected = (SR.id == model.Setor.id) ? true : false });
            }
            ViewBag.SetorID = items;*/

            List<SelectListItem> grauItems = new List<SelectListItem>();
            List<SelectListItem> departamentoItems = new List<SelectListItem>();
            List<SelectListItem> clienteItems = new List<SelectListItem>();
            List<SelectListItem> funcionarioItems = new List<SelectListItem>();
            List<SelectListItem> atribuicaoItems = new List<SelectListItem>();

            /*grauItems.Add(new SelectListItem { Text = "Muito Baixo", Value = "1", Selected = (1 == model.GrauUrgencia.id) ? true : false });
            grauItems.Add(new SelectListItem { Text = "Baixo", Value = "2", Selected = (2 == model.GrauUrgencia.id) ? true : false });
            grauItems.Add(new SelectListItem { Text = "Médio", Value = "3", Selected = (3 == model.GrauUrgencia.id) ? true : false });
            grauItems.Add(new SelectListItem { Text = "Alto", Value = "4", Selected = (4 == model.GrauUrgencia.id) ? true : false });
            grauItems.Add(new SelectListItem { Text = "Muito Alto", Value = "5", Selected = (5 == model.GrauUrgencia.id) ? true : false });*/

            /*clienteItems.Add(new SelectListItem { Text = "Bruno", Value = "1", Selected = (1 == model.Cliente.id) ? true : false });
            clienteItems.Add(new SelectListItem { Text = "Erick", Value = "2", Selected = (2 == model.Cliente.id) ? true : false });

            funcionarioItems.Add(new SelectListItem { Text = "Adilanne", Value = "1", Selected = (1 == model.Funcionario.id) ? true : false });
            funcionarioItems.Add(new SelectListItem { Text = "Kelvin", Value = "2", Selected = (2 == model.Funcionario.id) ? true : false });
            funcionarioItems.Add(new SelectListItem { Text = "Welison", Value = "3", Selected = (3 == model.Funcionario.id) ? true : false });*/

            IGrauUrgenciaRepositorio _grauRepo = new GrauUrgenciaRepositorio();
            foreach(var GP in _grauRepo.GetGrauUrgencia())
            {
                grauItems.Add(new SelectListItem { Text = GP.Nome, Value = GP.id.ToString(), Selected = (GP.id == model.GrauUrgencia.id) ? true : false }); 
            }

            IDepartamentoRepositorio _depRepo = new DepartamentoRepositorio();
            foreach (var DR in _depRepo.GetDepartamento())
            {
                departamentoItems.Add(new SelectListItem { Text = DR.Nome, Value = DR.id.ToString(), Selected = (DR.id == model.Departamento.id) ? true : false });
            }

            IClienteRepositorio _clienteRepo = new ClienteRepositorio();
            foreach (var CR in _clienteRepo.GetCliente())
            {
                clienteItems.Add(new SelectListItem { Text = CR.Nome, Value = CR.id.ToString(), Selected = (CR.id == model.Cliente.id) ? true : false });
            }

            IFuncionarioRepositorio _funcRepo = new FuncionarioRepositorio();
            foreach (var FR in _funcRepo.GetFuncionario())
            {
                funcionarioItems.Add(new SelectListItem { Text = FR.Nome, Value = FR.id.ToString(), Selected = (FR.id == model.Funcionario.id) ? true : false });
            }

            IAtribuicaoRepositorio _atribRepo = new AtribuicaoRepositorio();
            foreach (var AR in _atribRepo.GetAtribuicao())
            {
                atribuicaoItems.Add(new SelectListItem { Text = AR.Nome, Value = AR.id.ToString(), Selected = (AR.id == model.Atribuicao.id) ? true : false });
            }

            ViewBag.GrauUrgenciaID = grauItems;
            ViewBag.DepartamentoID = departamentoItems;
            ViewBag.ClienteID = clienteItems;
            ViewBag.FuncionarioID = funcionarioItems;
            ViewBag.AtribuicaoID = atribuicaoItems;

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Chamado chamado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.AtualizarChamado(chamado);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(chamado);
        }

        public ActionResult Delete(int id, bool? saveChangesError)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Problema ao deletar dados";
            }
            //Chamado chamado = _repositorio.GetChamadoPorID(id);
            Chamado chamado = _repositorio.GetChamado(ID: id).First();
            return View(chamado);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _repositorio.DeletarChamado(id);
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new System.Web.Routing.RouteValueDictionary { { "id", id }, { "saveChangesError", true } });
            }
            return RedirectToAction("Index");
        }
    }
}

PIM/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PIM.Models.Repository;
using PIM.Models.Objects;
using PIM.Controllers.Repository;
using System.Data;

namespace PIM.Controllers
{
    public class ClienteController : BaseController
    {
        private IClienteRepositorio _repositorio;

        public ClienteController() :this(new ClienteRepositorio())
        {
        }

        public ClienteController(IClienteRepositorio repositorio)
        {
            ViewBag.Title = "Clientes";
            _repositorio = repositorio;
        }

        public ActionResult Index()
        {
            var cliente = _repositorio.GetCliente();
            return View(cliente);
        }

        public ActionResult Details(int id)
        {
            Cliente model = _repositorio.GetCliente(ID: id).First();
            return View(model);
        }

        public ActionResult Create()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            IDepartamentoRepositorio _depRepo = new DepartamentoRepositorio();
            foreach (var DP in _depRepo.GetDepartamento())
            {
                items.Add(new SelectListItem { Text = DP.Nome, Value = DP.id.ToString() });
            }
            ViewBag.DepartamentoID = items;

            return View(new Cliente());
        }
        [HttpPost]
        public ActionResult Create(Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.InserirCliente(cliente);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(cliente);
        }

        public ActionResult Edit(int id)
        {
            Cliente model = _repositorio.GetCliente(ID: id).First();

            List<SelectListItem> items = new List<SelectListItem>();

            IDepartamentoRepositorio _depRepo = new DepartamentoRepositorio();
            foreach (var DP in _depRepo.GetDepartamento())
            {
                items.Add(new SelectListItem { Text = DP.Nome, Value = DP.id.ToString(), Selected = (DP.id == model.Departamento.id) ? true : false });
            }
            ViewBag.DepartamentoID = items;

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.AtualizarCliente(cliente);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(cliente);
        }

        public ActionResult Delete(int id, bool? saveChangesError)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Problema ao deletar dados";
            }
            Cliente cliente = _repositorio.GetCliente(ID: id).First();
            return View(cliente);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _repositorio.DeletarCliente(id);
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new System.Web.Routing.RouteValueDictionary { { "id", id }, { "saveChangesError", true } });
            }
            return RedirectToAction("Index");
        }

    }
}

PIM/Controllers/SetorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PIM.Models.Repository;
using PIM.Models;
using PIM.Controllers.Repository;
using System.Data;

namespace PIM.Controllers
{
    public class SetorController : BaseController
    {
        private ISetorRepositorio _repositorio;

        public SetorController() :this(new SetorRepositorio())
        {
        }

        public SetorController(ISetorRepositorio repositorio)
        {
            ViewBag.Title = "Setores";
            _repositorio = repositorio;
        }

        public ActionResult Index()
        {
            var setor = _repositorio.GetSetor();
            return View(setor);
        }

        public ActionResult Details(int id)
        {
            //Setor model = _repositorio.GetSetorPorID(id);
            Setor model = _repositorio.GetSetor(ID: id).First();
            return View(model);
        }

        public ActionResult Create()
        {
            return View(new Setor());
        }
        [HttpPost]
        public ActionResult Create(Setor setor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.InserirSetor(setor);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(setor);
        }

        public ActionResult Edit(int id)
        {
            Setor model = _repositorio.GetSetor(ID: id).First();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Setor setor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio.AtualizarSetor(setor);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Problemas ao salvar os dados...");
            }
            return View(setor);
        }

        public ActionResult Delete(int id, bool? saveChangesError)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Problema ao deletar dados";
            }
            //Setor setor = _repositorio.GetSetorPorID(id);
            Setor setor = _repositorio.GetSetor(ID: id).First();
            return View(setor);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                //ClienteModel cliente = _repositorio.GetClientePorID(id);
                _repositorio.DeletarSetor(id);
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new System.Web.Routing.RouteValueDictionary { { "id", id }, { "saveChangesError", true } });
            }
            return RedirectToAction("Index");
        }
    }
}

PIM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gerenciador De Chamados</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gerenciador De Chamados", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Setores", "Index", "Setor")</li>
                            <li>@Html.ActionLink("Departamentos", "Index", "Departamento")</li>
                            <li>@Html.ActionLink("Graus de Urgência", "Index", "GrauUrgencia")</li>
                            <li>@Html.ActionLink("Atribuições", "Index", "Atribuicao")</li>
                            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Funcionarios", "Index", "Funcionario")</li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Chamados", "Index", "Chamado")
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gerenciador De Chamados</p>
        </footer>
    </div>*@

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <img src="/img/logo.png" class="profile-img-card">
                <p class="profile-name-card">@Session["usuarioLogadoNome"]</p>
                <p id="link">
                    <!--<a id="linkMinhaConta" class="link" href="editarPerfil.html">Minha Conta</a>-->
                    <!--<span>&#124;</span>-->
                    @Html.ActionLink("Fechar Sessão", "Logoff", "Acesso")
                    <!--<a id="linhaFecharSessao" class="link" href="#">Fechar Sessão</a>-->
                </p>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu">
                        <i class="fas fa-desktop"></i>
                        Painel de Controle
                    </a>
                </li>
                <li>
                    <a href="#chamadoSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-ticket-alt"></i>
                        Chamados
                    </a>
                    <ul class="collapse list-unstyled" id="chamadoSubmenu">
                        <li>
                            @Html.ActionLink("Listar Chamados", "Index", "Chamado")
                            <!--<a href="chamados/ChamadosAbertos.html">Chamados Abertos</a>
                            <a href="chamados/ChamadosAtendimento.html">Chamados Em Atendimento</a>
                            <a href="chamados/ChamadosAtribuidos.html">Chamados Atribuidos</a>
                            <a href="chamados/ChamadosFechados.html">Chamados Fechados</a>
                            <a href="chamados/MeusChamados.html">Meus Chamados</a>-->
                        </li>
                    </ul>
                </li>
                @if (Session["usuarioLogadoTipo"] == "f")
                {
                    <li>
                        <a href="#cadastrosSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="fas fa-wrench"></i>
                            Cadastros
                        </a>
                        <ul class="collapse list-unstyled" id="cadastrosSubmenu">
                            <li>@Html.ActionLink("Setores", "Index", "Setor")</li>
                            <li>@Html.ActionLink("Departamentos", "Index", "Departamento")</li>
                            <li>@Html.ActionLink("Graus de Urgência", "Index", "GrauUrgencia")</li>
                            <li>@Html.ActionLink("Atribuições", "Index", "Atribuicao")</li>
                            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Funcionarios", "Index", "Funcionario")</li>
                        </ul>
                    </li>
                }
                <!--<li>
                    <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-user"></i>
                        Usuários
                    </a>
                    <ul class="collapse list-unstyled" id="userSubmenu">
                        <li>
                            <a href="Usuarios.html">Lista de Usuários</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#funcioSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-users"></i>
                        Funcionários
                    </a>
                    <ul class="collapse list-unstyled" id="funcioSubmenu">
                        <li>
                            <a href="Funcionarios.html">Listar Funcionários</a>
                        </li>
                    </ul>
                </li>-->
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                @*<div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="navbar-btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>*@
                    @RenderBody()
                </div>
            </nav>
        </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>
</html>

PIM/Views/Shared/_LayoutBACKUP.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gerenciador De Chamados</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gerenciador De Chamados", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Setores", "Index", "Setor")</li>
                            <li>@Html.ActionLink("Departamentos", "Index", "Departamento")</li>
                            <li>@Html.ActionLink("Graus de Urgência", "Index", "GrauUrgencia")</li>
                            <li>@Html.ActionLink("Atribuições", "Index", "Atribuicao")</li>
                            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Funcionarios", "Index", "Funcionario")</li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Chamados", "Index", "Chamado")
                        <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Chamados
                            <span class="caret"></span>
                        </a>-->
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gerenciador De Chamados</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>